plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.10'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.cloud.tools.jib' version '3.5.2'
}

group = 'com.studybuddy'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

jib {
	from {
		image = 'eclipse-temurin:25-jre'
	}

	to {
		image = 'toxicgeek/collaboration-service'
		tags = [ project.version.toString() ]
		auth {
			username = System.getenv('JIB_TO_AUTH_USERNAME') ?: ''
			password = System.getenv('JIB_TO_AUTH_PASSWORD') ?: ''
		}
	}

	container {
		ports = ['8082']
		creationTime = 'USE_CURRENT_TIMESTAMP'

		jvmFlags = [
				'-XX:MaxRAMPercentage=70.0',
				'-XX:+ExitOnOutOfMemoryError'
		]
	}
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.0.1"
	}
}


dependencies {
	// ----------------------------------------------------
	// Spring Boot Starters
	// ----------------------------------------------------
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// ----------------------------------------------------
	// Database
	// ----------------------------------------------------
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-mysql'
	runtimeOnly 'com.mysql:mysql-connector-j'

	// ----------------------------------------------------
	// API & Messaging
	// ----------------------------------------------------
	implementation 'org.springframework:spring-messaging'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.15'

	// ----------------------------------------------------
	// Utilities & File Storage
	// ----------------------------------------------------
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	implementation 'io.minio:minio:8.6.0'

	// ----------------------------------------------------
	// Testing
	// ----------------------------------------------------
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Config client
	implementation 'org.springframework.cloud:spring-cloud-starter-config'

	// Bus (RabbitMQ)
	implementation 'org.springframework.cloud:spring-cloud-starter-bus-amqp'

	// Actuator
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

tasks.named('test') {
	useJUnitPlatform()
}
